[packages.homebrew]
    casks = [
        "aerospace",
        "anki",
        "basecamp",
        "dropbox",
        "figma",
        "font-jetbrains-mono",
        "font-jetbrains-mono-nerd-font",
        "pocket-casts",
        "polypane",
        "visual-studio-code",
        "zoom"
    ]

    formulate = [
        "bat",
        "btop",
        "chezmoi",
        "exercism",
        "dysk",
        "eza",
        "fastfetch",
        "fnm",
        "fzf",
        "gh",
        "go",
        "jq",
        "lua",
        "neovim",
        "pnpm",
        "ripgrep",
        "starship",
        "tmux",
        "tree-sitter",
        "uv"
    ]
